dist: xenial
language: python
cache: pip
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install mock; fi
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - flake8
    - pytest --cov
after_success:
    - coveralls
