language: python
cache: pip
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install mock; fi
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
script:
    - flake8
    - nose2 --with-coverage
after_success:
    - coveralls
