language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install mock; fi
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
script:
    - flake8 --ignore=E501 lib/ tests/
    - nose2 --with-coverage
after_success:
    - coveralls
